#!/bin/bash
#
# Simple script to build OpenOCD
#

set -e
set -u

# Install necessary packages
sudo apt-get install libtool pkg-config texinfo libusb-dev libusb-1.0.0-dev libftdi-dev autoconf

# Clone
git clone https://github.com/openocd-org/openocd

# Enter directory
pushd openocd

# Create a new branch off the v0.12.0 release
git checkout -b v0.12.0_rz v0.12.0

# Apply an extra patch
# Manually download:
#    $ wget https://raw.githubusercontent.com/renesas-rz/rzg_openocd/master/0002-target-aarch64-Write-Memory-function-fix-for-self-mo.patch
#    $ mv 0002-*.patch ..
git am ../0002-target-aarch64-Write-Memory-function-fix-for-self-mo.patch

# Configure
./bootstrap
./configure --prefix ${PWD}/installdir --enable-jlink --enable-ftdi

# Build
make -j$(nproc)
make install

# Leave directory
popd

# Final Message
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "\n${RED}OpenOCD binary can be found in:  openocd/installdir/bin${NC}\n"
